"""stems

Revision ID: 376779d38f60
Revises: 8b72ae9c7f40
Create Date: 2026-10-04 05:08:51.278882
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '376779d38f60'
down_revision: Union[str, None] = '8b72ae9c7f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stems',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('VOCALS', 'INSTRUMENTAL', name='stem_kind'), nullable=False),
    sa.Column('blob_sha256', sa.String(length=64), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'kind', name='uq_stems_song_kind')
    )
    op.create_index(op.f('ix_stems_song_id'), 'stems', ['song_id'], unique=False)
    # server_default added by hand (autogenerate omitted it): 4 existing
    # ingest_jobs rows from earlier milestones' manual testing would
    # otherwise fail this NOT NULL ADD COLUMN outright.
    op.add_column(
        'ingest_jobs', sa.Column('step_index', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'ingest_jobs', sa.Column('step_total', sa.Integer(), nullable=False, server_default='1')
    )
    op.add_column('ingest_jobs', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingest_jobs', 'message')
    op.drop_column('ingest_jobs', 'step_total')
    op.drop_column('ingest_jobs', 'step_index')
    op.drop_index(op.f('ix_stems_song_id'), table_name='stems')
    op.drop_table('stems')
    # ### end Alembic commands ###
