"""song_analyses

Revision ID: 5a7a503e7300
Revises: 376779d38f60
Create Date: 2026-10-04 21:58:30.069830
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5a7a503e7300'
down_revision: Union[str, None] = '376779d38f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key_tonic', sa.String(length=2), nullable=True),
    sa.Column('key_mode', sa.String(length=5), nullable=True),
    sa.Column('key_confidence', sa.Float(), nullable=True),
    sa.Column('beat_count', sa.Integer(), nullable=False),
    sa.Column('downbeat_count', sa.Integer(), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('voiced_duration_s', sa.Float(), nullable=False),
    sa.Column('analysis_blob_sha256', sa.String(length=64), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_analyses_song_id'), 'song_analyses', ['song_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_analyses_song_id'), table_name='song_analyses')
    op.drop_table('song_analyses')
    # ### end Alembic commands ###
