"""blobs_songs

Revision ID: 8b72ae9c7f40
Revises: ec59312c31b8
Create Date: 2026-10-04 04:31:18.171815
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b72ae9c7f40'
down_revision: Union[str, None] = 'ec59312c31b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('songs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_blob_sha256', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='song_visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uploaded_by_user_id', 'source_blob_sha256', name='uq_songs_owner_blob')
    )
    op.create_index(op.f('ix_songs_source_blob_sha256'), 'songs', ['source_blob_sha256'], unique=False)
    op.create_index(op.f('ix_songs_uploaded_by_user_id'), 'songs', ['uploaded_by_user_id'], unique=False)
    op.add_column('ingest_jobs', sa.Column('song_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_ingest_jobs_song_id'), 'ingest_jobs', ['song_id'], unique=False)
    op.create_foreign_key(
        "fk_ingest_jobs_song_id_songs", "ingest_jobs", "songs", ["song_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_ingest_jobs_song_id_songs", "ingest_jobs", type_="foreignkey")
    op.drop_index(op.f('ix_ingest_jobs_song_id'), table_name='ingest_jobs')
    op.drop_column('ingest_jobs', 'song_id')
    op.drop_index(op.f('ix_songs_uploaded_by_user_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_source_blob_sha256'), table_name='songs')
    op.drop_table('songs')
    op.drop_table('blobs')
    # ### end Alembic commands ###
