"""ingest_jobs

Revision ID: a57f31ff729d
Revises: 
Create Date: 2026-10-04 00:40:59.217550
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a57f31ff729d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('source_blob_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('current_stage', sa.Enum('SEPARATION', 'STRUCTURE_BEATS', 'RMS_VAD', 'LYRICS', 'CTC_ALIGNMENT', 'F0', 'NOTE_GRID', name='ingest_job_stage'), nullable=True),
    sa.Column('separation_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('structure_beats_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('rms_vad_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('lyrics_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('ctc_alignment_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('f0_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('note_grid_status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ingest_job_status'), nullable=False),
    sa.Column('stage_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_jobs_status', 'ingest_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingest_jobs_status', table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
