"""performances

Revision ID: b9333fd88bad
Revises: a1b2c3d4e5f6
Create Date: 2026-10-06 22:02:05.300656
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b9333fd88bad'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performances',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('SOLO', 'SEED', 'JOIN', name='performance_kind'), nullable=False),
    sa.Column('parent_performance_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'SCORING', 'SUCCEEDED', 'FAILED', name='performance_status'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('audio_blob_sha256', sa.String(length=64), nullable=True),
    sa.Column('f0_blob_sha256', sa.String(length=64), nullable=True),
    sa.Column('analysis_blob_sha256', sa.String(length=64), nullable=True),
    sa.Column('score_overall', sa.Float(), nullable=True),
    sa.Column('pct_in_tune', sa.Float(), nullable=True),
    sa.Column('median_cents', sa.Float(), nullable=True),
    sa.Column('arrival_offset_ms_median', sa.Float(), nullable=True),
    sa.Column('octave_shift_semitones', sa.Integer(), nullable=True),
    sa.Column('alignment_warning', sa.Boolean(), nullable=False),
    sa.Column('offset_s', sa.Float(), nullable=True),
    sa.Column('latency_offset_ms', sa.Float(), nullable=True),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['audio_blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['f0_blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['parent_performance_id'], ['performances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_parent_performance_id'), 'performances', ['parent_performance_id'], unique=False)
    op.create_index(op.f('ix_performances_song_id'), 'performances', ['song_id'], unique=False)
    op.create_index(op.f('ix_performances_user_id'), 'performances', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping/recreating
    # song_embeddings' unique constraint/index as a unique=True index —
    # that's pre-existing drift between the a3e5f7c9b1d2 migration and
    # the SongEmbedding model (unrelated to W3/performances), left alone
    # per the plan's "avoid unrelated refactoring" instruction.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performances_user_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_song_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_parent_performance_id'), table_name='performances')
    op.drop_table('performances')
    # ### end Alembic commands ###
